### PR TITLE
SOLVED FLOATING POINT ISSUE

### PR DESCRIPTION
**Pull request by piyushverma001**
If there is some more issue let me know or else please merge it!
Cheers.

### CODE REVIEW

**Comment by haxer-max** [comment]
great, just can you remove the unnecessary 0s from the ending

**Comment by piyushverma001** [comment]
cool i'll do that

**Comment by piyushverma001** [comment]
It is now fixed and works like charm!

**Comment by haxer-max** [comment]
great, thanks

**Pull request merged**
